In [ ]:
from nba_api.stats.endpoints import leaguegamelog
import pandas as pd

file_path = '/Users/natemekonen/Desktop/Data_Projects/nba_2for1_analysis/data'

# Pull regular season and playoffs game ids
regular_df = leaguegamelog.LeagueGameLog(
    season = '2025-26',
    season_type_all_star = 'Regular Season',
    player_or_team_abbreviation = 'T'
).get_data_frames()[0]

playoffs_df = leaguegamelog.LeagueGameLog(
    season = '2025-26',
    season_type_all_star = 'Playoffs',
    player_or_team_abbreviation = 'T'
).get_data_frames()[0]

all_season = pd.concat([regular_df.assign(SEASON_TYPE="Regular Season"), playoffs_df.assign(SEASON_TYPE="Playoffs")], ignore_index=True)

game_ids = all_season['GAME_ID'].unique()

print(len(game_ids))

1315

In [ ]:
from nba_api.stats.endpoints import playbyplayv3
import pandas as pd
import time
import pyarrow

# Pull play by play data
all_pbp = []

for game_id in game_ids:
    try:
            pbp = playbyplayv3.PlayByPlayV3(
                game_id = game_id,
                start_period = 1,
                end_period = 10 
            )

            plays = pbp.get_data_frames()[0]
            plays['GAME_ID'] = game_id

            all_pbp.append(plays)

            print(f'Completed {game_id}')

            time.sleep(0.6)

    except Exception as e:
        print(f'Failed {game_id}: {e}')

# Combine all play dataframes into one 
pbp_df = pd.concat(all_pbp, ignore_index=True)

pbp_df.to_parquet(f'{file_path}/nba_2025_26_play_by_play.parquet', index=False)

Completed 0022500001
Completed 0022500002
Completed 0022500089
Completed 0022500080
Completed 0022500003
Completed 0022500081
Completed 0022500083
Completed 0022500088
Completed 0022500004
Completed 0022500082
Completed 0022500087
Completed 0022500085
Completed 0022500084
Completed 0022500086
Completed 0022500005
Completed 0022500006
Completed 0022500019
Completed 0022500091
Completed 0022500018
Completed 0022500090
Completed 0022500099
Completed 0022500097
Completed 0022500098
Completed 0022500095
Completed 0022500092
Completed 0022500096
Completed 0022500093
Completed 0022500094
Completed 0022500100
Completed 0022500103
Completed 0022500102
Completed 0022500104
Completed 0022500101
Completed 0022500110
Completed 0022500105
Completed 0022500108
Completed 0022500112
Completed 0022500113
Completed 0022500111
Completed 0022500106
Completed 0022500107
Completed 0022500109
Completed 0022500008
Completed 0022500116
Completed 0022500114
Completed 0022500120
Completed 0022500122
Completed 0022500118
Completed 0022500119
Completed 0022500115
Completed 0022500117
Completed 0022500007
Completed 0022500121
Completed 0022500125
Completed 0022500123
Completed 0022500126
Completed 0022500127
Completed 0022500124
Completed 0022500136
Completed 0022500130
Completed 0022500129
Completed 0022500133
Completed 0022500137
Completed 0022500135
Completed 0022500132
Completed 0022500131
Completed 0022500128
Completed 0022500134
Completed 0022500138
Completed 0022500141
Completed 0022500140
Completed 0022500139
Completed 0022500023
Completed 0022500020
Completed 0022500021
Completed 0022500025
Completed 0022500026
Completed 0022500022
Completed 0022500027
Completed 0022500024
Completed 0022500143
Completed 0022500145
Completed 0022500144
Completed 0022500142
Completed 0022500146
Completed 0022500147
Completed 0022500149
Completed 0022500153
Completed 0022500154
Completed 0022500148
Completed 0022500152
Completed 0022500150
Completed 0022500151
Completed 0022500155
Completed 0022500156
Completed 0022500159
Completed 0022500157
Completed 0022500163
Completed 0022500162
Completed 0022500158
Completed 0022500160
Completed 0022500164
Completed 0022500161
Completed 0022500166
Completed 0022500167
Completed 0022500169
Completed 0022500170
Completed 0022500165
Completed 0022500168
Completed 0022500175
Completed 0022500173
Completed 0022500171
Completed 0022500180
Completed 0022500181
Completed 0022500179
Completed 0022500172
Completed 0022500174
Completed 0022500177
Completed 0022500178
Completed 0022500176
Completed 0022500182
Completed 0022500036
Completed 0022500031
Completed 0022500028
Completed 0022500038
Completed 0022500032
Completed 0022500030
Completed 0022500029
Completed 0022500035
Completed 0022500034
Completed 0022500037
Completed 0022500033
Completed 0022500189
Completed 0022500184
Completed 0022500190
Completed 0022500187
Completed 0022500188
Completed 0022500185
Completed 0022500186
Completed 0022500183
Completed 0022500197
Completed 0022500192
Completed 0022500193
Completed 0022500196
Completed 0022500195
Completed 0022500194
Completed 0022500191
Completed 0022500205
Completed 0022500200
Completed 0022500204
Completed 0022500202
Completed 0022500206
Completed 0022500201
Completed 0022500203
Completed 0022500198
Completed 0022500199
Completed 0022500207
Completed 0022500208
Completed 0022500211
Completed 0022500209
Completed 0022500212
Completed 0022500210
Completed 0022500215
Completed 0022500221
Completed 0022500219
Completed 0022500223
Completed 0022500220
Completed 0022500222
Completed 0022500216
Completed 0022500217
Completed 0022500214
Completed 0022500224
Completed 0022500218
Completed 0022500213
Completed 0022500226
Completed 0022500225
Completed 0022500227
Completed 0022500044
Completed 0022500040
Completed 0022500039
Completed 0022500041
Completed 0022500042
Completed 0022500047
Completed 0022500045
Completed 0022500046
Completed 0022500043
Completed 0022500232
Completed 0022500230
Completed 0022500229
Completed 0022500228
Completed 0022500231
Completed 0022500235
Completed 0022500236
Completed 0022500239
Completed 0022500238
Completed 0022500234
Completed 0022500240
Completed 0022500233
Completed 0022500237
Completed 0022500246
Completed 0022500244
Completed 0022500242
Completed 0022500243
Completed 0022500247
Completed 0022500245
Completed 0022500241
Completed 0022500248
Completed 0022500250
Completed 0022500249
Completed 0022500254
Completed 0022500252
Completed 0022500253
Completed 0022500251
Completed 0022500259
Completed 0022500262
Completed 0022500256
Completed 0022500258
Completed 0022500263
Completed 0022500261
Completed 0022500255
Completed 0022500260
Completed 0022500257
Completed 0022500264
Completed 0022500266
Completed 0022500265
Completed 0022500267
Completed 0022500053
Completed 0022500049
Completed 0022500048
Completed 0022500056
Completed 0022500055
Completed 0022500050
Completed 0022500052
Completed 0022500051
Completed 0022500054
Completed 0022500269
Completed 0022500274
Completed 0022500270
Completed 0022500271
Completed 0022500273
Completed 0022500268
Completed 0022500272
Completed 0022500279
Completed 0022500277
Completed 0022500275
Completed 0022500281
Completed 0022500280
Completed 0022500282
Completed 0022500276
Completed 0022500278
Completed 0022500292
Completed 0022500285
Completed 0022500283
Completed 0022500290
Completed 0022500288
Completed 0022500284
Completed 0022500291
Completed 0022500289
Completed 0022500286
Completed 0022500287
Completed 0022500058
Completed 0022500057
Completed 0022500059
Completed 0022500064
Completed 0022500061
Completed 0022500063
Completed 0022500068
Completed 0022500067
Completed 0022500060
Completed 0022500065
Completed 0022500066
Completed 0022500062
Completed 0022500070
Completed 0022500074
Completed 0022500072
Completed 0022500073
Completed 0022500075
Completed 0022500077
Completed 0022500076
Completed 0022500069
Completed 0022500071
Completed 0022500078
Completed 0022500079
Completed 0022500293
Completed 0022500297
Completed 0022500295
Completed 0022500299
Completed 0022500294
Completed 0022500298
Completed 0022500300
Completed 0022500296
Completed 0022500306
Completed 0022500303
Completed 0022500304
Completed 0022500305
Completed 0022500307
Completed 0022500301
Completed 0022500302
Completed 0022500308
Completed 0022500312
Completed 0022500314
Completed 0022500310
Completed 0022500317
Completed 0022500316
Completed 0022500309
Completed 0022500315
Completed 0022500313
Completed 0022500311
Completed 0022500321
Completed 0022500320
Completed 0022500318
Completed 0022500319
Completed 0022500322
Completed 0022500323
Completed 0022500329
Completed 0022500328
Completed 0022500326
Completed 0022500325
Completed 0022500324
Completed 0022500330
Completed 0022500327
Completed 0022500332
Completed 0022500331
Completed 0022500337
Completed 0022500335
Completed 0022500333
Completed 0022500336
Completed 0022500334
Completed 0022500343
Completed 0022500339
Completed 0022500345
Completed 0022500348
Completed 0022500346
Completed 0022500342
Completed 0022500341
Completed 0022500349
Completed 0022500344
Completed 0022500340
Completed 0022500338
Completed 0022500347
Completed 0022500355
Completed 0022500350
Completed 0022500354
Completed 0022500351
Completed 0022500352
Completed 0022500356
Completed 0022500353
Completed 0022500357
Completed 0022500362
Completed 0022500360
Completed 0022500363
Completed 0022500358
Completed 0022500361
Completed 0022500359
Completed 0022500365
Completed 0022500364
Completed 0022500366
Completed 0022501202
Completed 0022501201
Completed 0022501203
Completed 0022501204
Completed 0022501207
Completed 0022501208
Completed 0022501206
Completed 0022501205
Completed 0022501215
Completed 0022501214
Completed 0022501211
Completed 0022501213
Completed 0022501210
Completed 0022501212
Completed 0022501209
Completed 0022501229
Completed 0022501230
Completed 0022501220
Completed 0022501219
Completed 0022501216
Completed 0022501217
Completed 0022501228
Completed 0022501221
Completed 0022501218
Completed 0022501223
Completed 0022501227
Completed 0022501224
Completed 0022501222
Completed 0022501225
Completed 0022501226
Completed 0022500368
Completed 0022500367
Completed 0022500373
Completed 0022500372
Completed 0022500377
Completed 0022500378
Completed 0022500380
Completed 0022500370
Completed 0022500369
Completed 0022500374
Completed 0022500379
Completed 0022500371
Completed 0022500375
Completed 0022500376
Completed 0022500385
Completed 0022500382
Completed 0022500383
Completed 0022500381
Completed 0022500384
Completed 0022500393
Completed 0022500389
Completed 0022500387
Completed 0022500392
Completed 0022500394
Completed 0022500388
Completed 0022500386
Completed 0022500395
Completed 0022500391
Completed 0022500390
Completed 0022500400
Completed 0022500397
Completed 0022500398
Completed 0022500401
Completed 0022500399
Completed 0022500396
Completed 0022500407
Completed 0022500403
Completed 0022500408
Completed 0022500406
Completed 0022500405
Completed 0022500402
Completed 0022500404
Completed 0022500416
Completed 0022500410
Completed 0022500420
Completed 0022500413
Completed 0022500418
Completed 0022500421
Completed 0022500417
Completed 0022500414
Completed 0022500419
Completed 0022500411
Completed 0022500412
Completed 0022500415
Completed 0022500422
Completed 0022500409
Completed 0022500013
Completed 0022500009
Completed 0022500010
Completed 0022500011
Completed 0022500012
Completed 0022500424
Completed 0022500426
Completed 0022500427
Completed 0022500429
Completed 0022500431
Completed 0022500425
Completed 0022500430
Completed 0022500423
Completed 0022500428
Completed 0022500439
Completed 0022500435
Completed 0022500433
Completed 0022500436
Completed 0022500434
Completed 0022500432
Completed 0022500440
Completed 0022500438
Completed 0022500437
Completed 0022500442
Completed 0022500444
Completed 0022500446
Completed 0022500441
Completed 0022500445
Completed 0022500443
Completed 0022500452
Completed 0022500449
Completed 0022500454
Completed 0022500451
Completed 0022500453
Completed 0022500448
Completed 0022500457
Completed 0022500456
Completed 0022500455
Completed 0022500450
Completed 0022500447
Completed 0022500458
Completed 0022500461
Completed 0022500459
Completed 0022500460
Completed 0022500463
Completed 0022500467
Completed 0022500464
Completed 0022500465
Completed 0022500470
Completed 0022500468
Completed 0022500466
Completed 0022500462
Completed 0022500469
Completed 0022500471
Completed 0022500473
Completed 0022500474
Completed 0022500475
Completed 0022500472
Completed 0022500477
Completed 0022500479
Completed 0022500480
Completed 0022500476
Completed 0022500483
Completed 0022500482
Completed 0022500484
Completed 0022500478
Completed 0022500485
Completed 0022500481
Completed 0022500486
Completed 0022500487
Completed 0022500490
Completed 0022500488
Completed 0022500492
Completed 0022500493
Completed 0022500489
Completed 0022500491
Completed 0022500498
Completed 0022500496
Completed 0022500495
Completed 0022500499
Completed 0022500500
Completed 0022500494
Completed 0022500497
Completed 0022500501
Completed 0022500502
Completed 0022500507
Completed 0022500505
Completed 0022500509
Completed 0022500506
Completed 0022500504
Completed 0022500503
Completed 0022500508
Completed 0022500513
Completed 0022500511
Completed 0022500510
Completed 0022500515
Completed 0022500512
Completed 0022500514
Completed 0022500521
Completed 0022500522
Completed 0022500518
Completed 0022500524
Completed 0022500527
Completed 0022500523
Completed 0022500525
Completed 0022500516
Completed 0022500519
Completed 0022500520
Completed 0022500517
Completed 0022500526
Completed 0022500530
Completed 0022500528
Completed 0022500531
Completed 0022500535
Completed 0022500538
Completed 0022500533
Completed 0022500540
Completed 0022500539
Completed 0022500536
Completed 0022500532
Completed 0022500537
Completed 0022500534
Completed 0022500541
Completed 0022500542
Completed 0022500543
Completed 0022500545
Completed 0022500547
Completed 0022500546
Completed 0022500544
Completed 0022500552
Completed 0022500549
Completed 0022500551
Completed 0022500548
Completed 0022500550
Completed 0022500555
Completed 0022500557
Completed 0022500553
Completed 0022500556
Completed 0022500554
Completed 0022500561
Completed 0022500559
Completed 0022500560
Completed 0022500562
Completed 0022500558
Completed 0022500563
Completed 0022500566
Completed 0022500564
Completed 0022500570
Completed 0022500568
Completed 0022500569
Completed 0022500567
Completed 0022500565
Completed 0022500574
Completed 0022500576
Completed 0022500571
Completed 0022500572
Completed 0022500573
Completed 0022500575
Completed 0022500577
Completed 0022500584
Completed 0022500578
Completed 0022500579
Completed 0022500585
Completed 0022500582
Completed 0022500581
Completed 0022500583
Completed 0022500580
Completed 0022500586
Completed 0022500591
Completed 0022500587
Completed 0022500588
Completed 0022500589
Completed 0022500592
Completed 0022500590
Completed 0022500598
Completed 0022500596
Completed 0022500595
Completed 0022500601
Completed 0022500597
Completed 0022500593
Completed 0022500594
Completed 0022500600
Completed 0022500599
Completed 0022500603
Completed 0022500602
Completed 0022500606
Completed 0022500607
Completed 0022500604
Completed 0022500605
Completed 0022500610
Completed 0022500016
Completed 0022500609
Completed 0022500611
Completed 0022500015
Completed 0022500014
Completed 0022500017
Completed 0022500612
Completed 0022500608
Completed 0022500616
Completed 0022500613
Completed 0022500619
Completed 0022500615
Completed 0022500618
Completed 0022500614
Completed 0022500617
Completed 0022500622
Completed 0022500621
Completed 0022500626
Completed 0022500625
Completed 0022500623
Completed 0022500620
Completed 0022500624
Completed 0022500631
Completed 0022500627
Completed 0022500628
Completed 0022500634
Completed 0022500632
Completed 0022500630
Completed 0022500629
Completed 0022500633
Completed 0022500637
Completed 0022500641
Completed 0022500636
Completed 0022500642
Completed 0022500638
Completed 0022500639
Completed 0022500640
Completed 0022500635
Completed 0022500643
Completed 0022500646
Completed 0022500649
Completed 0022500647
Completed 0022500648
Completed 0022500645
Completed 0022500644
Completed 0022500656
Completed 0022500655
Completed 0022500650
Completed 0022500654
Completed 0022500653
Completed 0022500663
Completed 0022500658
Completed 0022500659
Completed 0022500657
Completed 0022500660
Completed 0022500661
Completed 0022500662
Completed 0022500669
Completed 0022500665
Completed 0022500666
Completed 0022500664
Completed 0022500667
Completed 0022500670
Completed 0022500668
Completed 0022500677
Completed 0022500675
Completed 0022500674
Completed 0022500672
Completed 0022500679
Completed 0022500678
Completed 0022500673
Completed 0022500671
Completed 0022500676
Completed 0022500686
Completed 0022500684
Completed 0022500680
Completed 0022500685
Completed 0022500682
Completed 0022500529
Completed 0022500683
Completed 0022500681
Completed 0022500694
Completed 0022500690
Completed 0022500687
Completed 0022500693
Completed 0022500689
Completed 0022500691
Completed 0022500695
Completed 0022500696
Completed 0022500688
Completed 0022500700
Completed 0022500698
Completed 0022500699
Completed 0022500697
Completed 0022500692
Completed 0022500701
Completed 0022500704
Completed 0022500708
Completed 0022500703
Completed 0022500709
Completed 0022500710
Completed 0022500707
Completed 0022500711
Completed 0022500706
Completed 0022500702
Completed 0022500705
Completed 0022500714
Completed 0022500713
Completed 0022500715
Completed 0022500712
Completed 0022500719
Completed 0022500718
Completed 0022500723
Completed 0022500717
Completed 0022500724
Completed 0022500725
Completed 0022500720
Completed 0022500721
Completed 0022500722
Completed 0022500716
Completed 0022500727
Completed 0022500726
Completed 0022500731
Completed 0022500730
Completed 0022500728
Completed 0022500732
Completed 0022500729
Completed 0022500734
Completed 0022500740
Completed 0022500739
Completed 0022500738
Completed 0022500736
Completed 0022500735
Completed 0022500737
Completed 0022500733
Completed 0022500744
Completed 0022500742
Completed 0022500743
Completed 0022500745
Completed 0022500746
Completed 0022500741
Completed 0022500747
Completed 0022500750
Completed 0022500754
Completed 0022500755
Completed 0022500756
Completed 0022500749
Completed 0022500748
Completed 0022500751
Completed 0022500752
Completed 0022500753
Completed 0022500760
Completed 0022500757
Completed 0022500759
Completed 0022500758
Completed 0022500765
Completed 0022500762
Completed 0022500764
Completed 0022500770
Completed 0022500766
Completed 0022500769
Completed 0022500763
Completed 0022500767
Completed 0022500768
Completed 0022500761
Completed 0022500771
Completed 0022500773
Completed 0022500774
Completed 0022500772
Completed 0022500783
Completed 0022500779
Completed 0022500780
Completed 0022500777
Completed 0022500785
Completed 0022500786
Completed 0022500788
Completed 0022500781
Completed 0022500775
Completed 0022500778
Completed 0022500776
Completed 0022500784
Completed 0022500787
Completed 0022500782
Completed 0022500790
Completed 0022500789
Completed 0022500791
Completed 0022500793
Completed 0022500796
Completed 0022500800
Completed 0022500795
Completed 0022500794
Completed 0022500798
Completed 0022500797
Completed 0022500799
Completed 0022500801
Completed 0022500792
Completed 0022500806
Completed 0022500808
Completed 0022500803
Completed 0022500810
Completed 0022500804
Completed 0022500805
Completed 0022500802
Completed 0022500807
Completed 0022500809
Completed 0022500816
Completed 0022500811
Completed 0022500812
Completed 0022500815
Completed 0022500814
Completed 0022500813
Completed 0022500824
Completed 0022500818
Completed 0022500825
Completed 0022500827
Completed 0022500821
Completed 0022500826
Completed 0022500817
Completed 0022500819
Completed 0022500823
Completed 0022500820
Completed 0022500822
Completed 0022500829
Completed 0022500828
Completed 0022500830
Completed 0022500841
Completed 0022500833
Completed 0022500835
Completed 0022500840
Completed 0022500831
Completed 0022500839
Completed 0022500834
Completed 0022500832
Completed 0022500838
Completed 0022500836
Completed 0022500837
Completed 0022500845
Completed 0022500843
Completed 0022500842
Completed 0022500847
Completed 0022500846
Completed 0022500844
Completed 0022500857
Completed 0022500851
Completed 0022500852
Completed 0022500848
Completed 0022500849
Completed 0022500855
Completed 0022500853
Completed 0022500854
Completed 0022500856
Completed 0022500850
Completed 0022500859
Completed 0022500860
Completed 0022500862
Completed 0022500858
Completed 0022500861
Completed 0022500863
Completed 0022500865
Completed 0022500867
Completed 0022500866
Completed 0022500864
Completed 0022500871
Completed 0022500869
Completed 0022500868
Completed 0022500875
Completed 0022500872
Completed 0022500874
Completed 0022500873
Completed 0022500878
Completed 0022500876
Completed 0022500877
Completed 0022500870
Completed 0022500881
Completed 0022500880
Completed 0022500882
Completed 0022500879
Completed 0022500890
Completed 0022500886
Completed 0022500887
Completed 0022500885
Completed 0022500888
Completed 0022500892
Completed 0022500889
Completed 0022500884
Completed 0022500891
Completed 0022500883
Completed 0022500893
Completed 0022500898
Completed 0022500895
Completed 0022500896
Completed 0022500897
Completed 0022500894
Completed 0022500903
Completed 0022500901
Completed 0022500899
Completed 0022500905
Completed 0022500907
Completed 0022500904
Completed 0022500900
Completed 0022500906
Completed 0022500902
Completed 0022500911
Completed 0022500914
Completed 0022500912
Completed 0022500910
Completed 0022500913
Completed 0022500908
Completed 0022500909
Completed 0022500915
Completed 0022500916
Completed 0022500917
Completed 0022500920
Completed 0022500919
Completed 0022500918
Completed 0022500922
Completed 0022500926
Completed 0022500929
Completed 0022500928

In [29]:
# Read in parquet file with play by play data
pbp_plays = pd.read_parquet(f'{file_path}/nba_2025_26_play_by_play.parquet')

pd.set_option('display.max_columns', None)

# Sort the df in chronological order
pbp_plays = pbp_plays.sort_values(
    ['GAME_ID', 'period', 'actionNumber']
)

pbp_plays.head()

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId,GAME_ID
0,0022500001,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (7:44 PM EST),period,start,1,0,1,0022500001
1,0022500001,4,PT12M00.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,0,0,,0,,,0,h,Jump Ball Holmgren vs. Adams: Tip to Thompson,Jump Ball,,1,0,2,0022500001
2,0022500001,8,PT11M36.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,-179,179,25,Missed,1,,,0,v,MISS Sengun 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,3,0022500001
3,0022500001,9,PT11M31.00S,1,1610612760,OKC,1641717,Wallace,C. Wallace,0,0,0,,0,,,0,h,Wallace REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,4,0022500001
4,0022500001,10,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,13,1,Made,1,2,0,2,h,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,Made Shot,Cutting Layup Shot,1,2,5,0022500001

In [30]:
# Define function to convert clock columns into seconds
def clock_to_seconds(clock):

    if pd.isna(clock):
        return None

    clock = str(clock)

    clock = (
        clock
        .replace('PT', '')
        .replace('S', '')
    )

    minutes, seconds = clock.split('M')

    return int(minutes) * 60 + float(seconds)

In [ ]:
# Define function to parse data and create possessions
import re

def create_possessions(game_df):
    
    possessions = []
    possession_id = 1
    current_events = []
    possession_team = None
    start_clock = None
    free_throw_total = None
    free_throw_number = None

    def save_possession():

        nonlocal possession_id
        nonlocal current_events
        nonlocal start_clock
        nonlocal possession_team

        if len(current_events) == 0:
            return

        # Remove blocks from output
        output_events = [
            e for e in current_events
            if not (
                (pd.isna(e['actionType']) or e['actionType'] == '')
                and pd.notna(e.get('description'))
                and 'BLOCK' in str(e['description'])
            )
        ]

        # Get the first shot in the possession
        first_shot = next(
            (e for e in output_events if e.get('actionType') in ['Made Shot', 'Missed Shot']),
            None
        )

        if first_shot is not None:
            first_shot_seconds = round(clock_to_seconds(first_shot.get('clock')), 0)
            first_shot_player = first_shot.get('playerNameI')
            first_shot_result = first_shot.get('shotResult')
            first_shot_value = first_shot.get('shotValue')
            first_shot_x_legacy = first_shot.get('xLegacy')
            first_shot_y_legacy = first_shot.get('yLegacy')
            first_shot_distance = first_shot.get('shotDistance')
            first_shot_subtype = first_shot.get('subType')

        else:
            first_shot_seconds = None
            first_shot_player = None
            first_shot_result = None
            first_shot_value = None
            first_shot_x_legacy = None
            first_shot_y_legacy = None
            first_shot_distance = None
            first_shot_subtype = None

        possessions.append({
            'GAME_ID': current_events[0]['GAME_ID'],
            'POSSESSION_ID': possession_id,
            'PERIOD': current_events[0]['period'],
            'TEAM': current_events[-1].get('teamTricode'),
            'START_CLOCK': start_clock,
            'END_CLOCK': current_events[-1]['clock'],
            'EVENTS': len(output_events),
            'ACTION_TYPES':
                ', '.join(
                    [
                        (
                            'Steal'
                            if ((pd.isna(e['actionType']) or e['actionType'] == '') and 'STEAL' in str(e.get('description')))
                            else str(e['actionType'])
                        )
                        for e in output_events
                    ]
                ),
            'CLOCK_LIST': ', '.join([str(e['clock']) for e in output_events]),
            'SHOT_VALUE': next(
                (
                    e['shotValue']
                    for e in reversed(output_events)
                    if pd.notna(e.get('shotValue'))
                ),
                None
            ),
            'TEAM_ID': current_events[-1].get('teamId'),
            'PLAYER_ID': current_events[-1].get('personId'),
            'PLAYER_NAME': current_events[-1].get('playerNameI'),
            'HOME_SCORE': current_events[-1].get('scoreHome'),
            'AWAY_SCORE': current_events[-1].get('scoreAway'),
            'X_LEGACY': current_events[-1].get('xLegacy'),
            'Y_LEGACY': current_events[-1].get('yLegacy'),
            'SHOT_DISTANCE': current_events[-1].get('shotDistance'),
            'SHOT_RESULT': current_events[-1].get('shotResult'),
            'SUBTYPE': current_events[-1].get('subType'),
            'FIRST_SHOT_SECONDS': first_shot_seconds,
            'FIRST_SHOT_PLAYER': first_shot_player,
            'FIRST_SHOT_RESULT': first_shot_result,
            'FIRST_SHOT_VALUE': first_shot_value,
            'FIRST_SHOT_X_LEGACY': first_shot_x_legacy,
            'FIRST_SHOT_Y_LEGACY': first_shot_y_legacy,
            'FIRST_SHOT_DISTANCE': first_shot_distance,
            'FIRST_SHOT_SUBTYPE': first_shot_subtype,
            'EVENT_LIST': ' | '.join([str(e['description']) for e in output_events])
        })

        possession_id += 1
        current_events = []
        start_clock = None
        possession_team = None

    for _, row in game_df.iterrows():

        action = row['actionType']

        if action == 'Substitution':
            continue

        # Convert row to dictionary
        event = row.to_dict()

        # Ignore quarter start messages
        if action == 'period' and len(current_events) == 0:
            continue

        # Start possession
        if len(current_events) == 0:
            start_clock = row['clock']

            # team responsible for event
            if pd.notna(row['teamTricode']):
                possession_team = row['teamTricode']

        current_events.append(event)

        # Track shots
        if action in ['Made Shot', 'Missed Shot']:
            last_shot_team = row['teamTricode']

        # Track free throws
        if action == 'Free Throw':
            match = re.search(
                r'Free Throw (\d+) of (\d+)',
                str(row['description'])
            )
            if match:
                free_throw_number = int(match.group(1))
                free_throw_total = int(match.group(2))

        possession_end = False

        # Made basket ends possession
        if action == 'Made Shot':
            possession_end = True

        # Turnover ends possession
        elif action == 'Turnover':
            possession_end = True

        # Missed shot followed by defensive rebound
        # Missed shot followed by block + defensive rebound
        if action == 'Missed Shot':
            current_idx = game_df.index.get_loc(row.name)
            future_events = game_df.iloc[current_idx + 1:]

            for _, next_row in future_events.iterrows():
                # Defensive rebound ends possession
                if next_row['actionType'] == 'Rebound':
                    rebound_team = next_row['teamTricode']

                    if (
                        pd.notna(rebound_team)
                        and rebound_team != row['teamTricode']
                        and rebound_team != 'Unknown'
                    ):
                        possession_end = True

                    break

                # Ignore blocks, steals, and blank action types
                if (
                    (pd.isna(next_row['actionType']) or next_row['actionType'] == '')
                    and (
                        'BLOCK' in str(next_row['description'])
                        or 'STEAL' in str(next_row['description'])
                    )
                ):
                    continue

                # Stop searching if another shot happens
                if next_row['actionType'] in [
                    'Made Shot',
                    'Missed Shot'
                ]:
                    break

        # Final free throw
        elif action == 'Free Throw':
            if (
                free_throw_number is not None
                and free_throw_total is not None
                and free_throw_number == free_throw_total
            ):
                possession_end = True

        # End of quarter
        elif action == 'period':
            possession_end = True

        if possession_end:
            save_possession()
            free_throw_number = None
            free_throw_total = None

    return possessions

In [158]:
import numpy as np

# Group pbp data into games and create possessions for each
all_possessions = []

for game_id, game in pbp_plays.groupby('GAME_ID'):

    game = (
        game
        .sort_values(['period', 'actionNumber'])
        .copy()
    )

    game['scoreHome'] = (
        game['scoreHome']
        .replace('', np.nan)
        .ffill()
        .fillna(0)
    )

    game['scoreAway'] = (
        game['scoreAway']
        .replace('', np.nan)
        .ffill()
        .fillna(0)
    )

    game_possessions = create_possessions(game)

    all_possessions.extend(game_possessions)

In [159]:
import re

# Define function to get free throw points
def get_free_throw_points(event_list):
    
    if pd.isna(event_list):
        return 0
    
    points = 0
    
    for event in event_list.split(' | '):
        
        if 'Free Throw' in event:
            
            # Missed free throw
            if 'MISS' in event.upper():
                continue
            
            # Made free throw
            points += 1
    
    return points

In [ ]:
import numpy as np

possession_df = pd.DataFrame(all_possessions)

# Convert clock columns to seconds
possession_df['START_SECONDS'] = (
    possession_df['START_CLOCK']
    .apply(clock_to_seconds)
    .round(0)
    .astype(int)
)

possession_df['END_SECONDS'] = (
    possession_df['END_CLOCK']
    .apply(clock_to_seconds)
    .round(0)
    .astype(int)
)

possession_df['CLOCK_SECONDS_LIST'] = (
    possession_df['CLOCK_LIST']
    .str.split(',')
    .apply(
        lambda clocks: ', '.join(
            str(round(clock_to_seconds(c.strip())))
            for c in clocks
        )
    )
)

# Convert scores to numeric
possession_df['HOME_SCORE'] = pd.to_numeric(
    possession_df['HOME_SCORE'],
    errors='coerce'
)

possession_df['AWAY_SCORE'] = pd.to_numeric(
    possession_df['AWAY_SCORE'],
    errors='coerce'
)

# Get the final action in the possession
last_action = possession_df['ACTION_TYPES'].str.split(',').str[-1].str.strip()

# Get the first action in the possession
first_action = possession_df['ACTION_TYPES'].str.split(',').str[0].str.strip()

# Calculate possession length
possession_df['POSS_LENGTH'] = np.where(
    last_action.isin(['Made Shot', 'Missed Shot']),
    possession_df['START_SECONDS'] - possession_df['END_SECONDS'],
    np.nan
)

# Handle possession length where the shot is the only action
only_shot = (possession_df['EVENTS'] == 1) & (last_action.isin(['Made Shot', 'Missed Shot']))

possession_df.loc[only_shot, 'POSS_LENGTH'] = (possession_df['END_SECONDS'].shift(1) - possession_df['START_SECONDS'])

# Handle Missed Shot -> other event -> Made/Missed Shot
three_event_shot = (
    (possession_df['EVENTS'] == 3)
    &
    (first_action == 'Missed Shot')
    &
    (last_action.isin(['Made Shot', 'Missed Shot']))
)

possession_df.loc[three_event_shot, 'POSS_LENGTH'] = (
    possession_df['END_SECONDS'].shift(1)
    -
    possession_df['END_SECONDS']
)

# Find how many seconds passed before the first shot in the possession
possession_df['TIME_UNTIL_FIRST_SHOT'] = round(
    possession_df['START_SECONDS'] - possession_df['FIRST_SHOT_SECONDS'],
    2
)

# Create official possession time
possession_df['SHOT_TIME_FOR_ANALYSIS'] = np.where(
    possession_df['EVENTS'] <= 2,
    possession_df['POSS_LENGTH'],
    np.where(
        first_action == 'Missed Shot',
        possession_df['POSS_LENGTH'],
        possession_df['TIME_UNTIL_FIRST_SHOT']
    )
)

# Check if the possession is a 2-for-1 attempt
possession_df['TWO_FOR_ONE_ATTEMPT'] = np.where(
    (
        possession_df['START_SECONDS'].between(34, 40)
        &
        (possession_df['SHOT_TIME_FOR_ANALYSIS'] <= 7)
        &
        ((possession_df['PERIOD'] != 4) |
            ((possession_df['PERIOD'] == 4) & ((possession_df['HOME_SCORE'] - possession_df['AWAY_SCORE']).abs() <= 10))
        )
    ),
    1,
    0
)

# Check if the possession is not a 2-for-1 attempt
possession_df['NO_TWO_FOR_ONE_ATTEMPT'] = np.where(
    (
        possession_df['POSS_LENGTH'].notna()
        &
        possession_df['START_SECONDS'].between(34, 40)
        &
        (possession_df['SHOT_TIME_FOR_ANALYSIS'] > 7)
        &
        (possession_df['END_SECONDS'] <= 24)
        & 
        ((possession_df['PERIOD'] != 4) | 
                ((possession_df['PERIOD'] == 4) & ((possession_df['HOME_SCORE'] - possession_df['AWAY_SCORE']).abs() <= 10))
        )
    ),
    1,
    0
)

# Create lookup of matchups
team_lookup = (
    possession_df.groupby('GAME_ID')['TEAM']
    .unique()
    .apply(list)
)

# Create opponent column
possession_df['OPPONENT'] = possession_df.apply(
    lambda x: team_lookup[x['GAME_ID']][
        1 - team_lookup[x['GAME_ID']].index(x['TEAM'])
    ],
    axis=1
)

# Calculate free throw points
possession_df['FREE_THROW_PTS'] = (
    possession_df['EVENT_LIST']
    .apply(get_free_throw_points)
)

# Create points on possession column
possession_df['POSS_PTS'] = np.where(
    possession_df['FREE_THROW_PTS'] > 0,
    possession_df['FREE_THROW_PTS'],
    np.where(
        possession_df['SHOT_RESULT'] == 'Made',
        possession_df['SHOT_VALUE'],
        np.where(
            possession_df['SHOT_RESULT'] == 'Missed',
            0,
            np.nan
        )
    )
)

possession_df['POSS_PTS'] = possession_df['POSS_PTS'].fillna(0)

possession_df.head()

,GAME_ID,POSSESSION_ID,PERIOD,TEAM,START_CLOCK,END_CLOCK,EVENTS,ACTION_TYPES,CLOCK_LIST,SHOT_VALUE,TEAM_ID,PLAYER_ID,PLAYER_NAME,HOME_SCORE,AWAY_SCORE,X_LEGACY,Y_LEGACY,SHOT_DISTANCE,SHOT_RESULT,SUBTYPE,FIRST_SHOT_SECONDS,FIRST_SHOT_PLAYER,FIRST_SHOT_RESULT,FIRST_SHOT_VALUE,FIRST_SHOT_X_LEGACY,FIRST_SHOT_Y_LEGACY,FIRST_SHOT_DISTANCE,FIRST_SHOT_SUBTYPE,EVENT_LIST,START_SECONDS,END_SECONDS,CLOCK_SECONDS_LIST,POSS_LENGTH,TIME_UNTIL_FIRST_SHOT,SHOT_TIME_FOR_ANALYSIS,TWO_FOR_ONE_ATTEMPT,NO_TWO_FOR_ONE_ATTEMPT,OPPONENT,FREE_THROW_PTS,POSS_PTS
0,0022500001,1,1,HOU,PT12M00.00S,PT11M36.00S,2,"Jump Ball, Missed Shot","PT12M00.00S, PT11M36.00S",3,1610612745,1630578,A. Sengun,0,0,-179,179,25,Missed,Jump Shot,696.0,A. Sengun,Missed,3.0,-179.0,179.0,25.0,Jump Shot,Jump Ball Holmgren vs. Adams: Tip to Thompson ...,720,696,"720, 696",24.0,24.0,24.0,0,0,OKC,0,0.0
1,0022500001,2,1,OKC,PT11M31.00S,PT11M26.00S,2,"Rebound, Made Shot","PT11M31.00S, PT11M26.00S",2,1610612760,1631096,C. Holmgren,2,0,0,13,1,Made,Cutting Layup Shot,686.0,C. Holmgren,Made,2.0,0.0,13.0,1.0,Cutting Layup Shot,Wallace REBOUND (Off:0 Def:1) | Holmgren 1' Cu...,691,686,"691, 686",5.0,5.0,5.0,0,0,HOU,0,2.0
2,0022500001,3,1,OKC,PT11M26.00S,PT11M26.00S,2,"Foul, Free Throw","PT11M26.00S, PT11M26.00S",0,1610612760,1631096,C. Holmgren,3,0,0,0,0,,Free Throw 1 of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Smith Jr. S.FOUL (P1.T1) (E.Dalen) | Holmgren ...,686,686,"686, 686",NaN,NaN,NaN,0,0,HOU,1,1.0
3,0022500001,4,1,HOU,PT11M08.00S,PT11M02.00S,3,"Missed Shot, Rebound, Made Shot","PT11M08.00S, PT11M04.00S, PT11M02.00S",2,1610612745,1631095,J. Smith Jr.,3,2,-7,-5,1,Made,Putback Layup Shot,668.0,A. Thompson,Missed,3.0,233.0,0.0,0.0,Jump Shot,MISS Thompson 3PT Jump Shot | Smith Jr. REBOUN...,668,662,"668, 664, 662",24.0,0.0,24.0,0,0,OKC,0,2.0
4,0022500001,5,1,OKC,PT10M50.00S,PT10M50.00S,1,Made Shot,PT10M50.00S,2,1610612760,1631096,C. Holmgren,5,2,64,39,7,Made,Floating Jump shot,650.0,C. Holmgren,Made,2.0,64.0,39.0,7.0,Floating Jump shot,Holmgren 7' Floating Jump Shot (5 PTS) (Wallac...,650,650,650,12.0,0.0,12.0,0,0,HOU,0,2.0

In [ ]:
# Sort the full possession dataframe chronologically
possession_df = possession_df.sort_values(
    ['GAME_ID', 'PERIOD', 'POSSESSION_ID']
).reset_index(drop=True)

# Number of later possessions for the same team in the same quarter
possession_df['LATER_TEAM_POSSESSIONS'] = (
    possession_df
    .groupby(['GAME_ID', 'PERIOD', 'TEAM'])
    .cumcount(ascending=False)
)

# Did the team get another possession later in the quarter after a two-for-one?
possession_df['TWO_FOR_ONE_SECOND_POSSESSION?'] = np.where(
    (
        (possession_df['TWO_FOR_ONE_ATTEMPT'] == 1)
        &
        (possession_df['LATER_TEAM_POSSESSIONS'] > 0)
    ),
    1,
    np.where(
        possession_df['TWO_FOR_ONE_ATTEMPT'] == 1,
        0,
        np.nan
    )
)

# Did the team get another possession later in the quarter after running the clock?
possession_df['NON_TWO_FOR_ONE_SECOND_POSSESSION?'] = np.where(
    (
        (possession_df['NO_TWO_FOR_ONE_ATTEMPT'] == 1)
        &
        (possession_df['LATER_TEAM_POSSESSIONS'] > 0)
    ),
    1,
    np.where(
        possession_df['NO_TWO_FOR_ONE_ATTEMPT'] == 1,
        0,
        np.nan
    )
)

# Get the points scored on possession after two-for-one
def next_team_possession_points(group):

    next_pts = []

    for i in range(len(group)):

        if i < len(group) - 1:
            next_pts.append(
                group.iloc[i + 1]['POSS_PTS']
            )
        else:
            next_pts.append(np.nan)

    return pd.Series(
        next_pts,
        index=group.index
    )

# Create column that shows pts on the possession after two-for-one
possession_df['SECOND_POSSESSION_PTS'] = (
    possession_df
    .groupby(
        ['GAME_ID', 'PERIOD', 'TEAM'],
        group_keys=False
    )
    .apply(next_team_possession_points)
)

# Get first shot result from the team's next possession
def next_team_possession_shot_result(group):

    next_result = []

    for i in range(len(group)):

        if i < len(group) - 1:
            next_result.append(
                group.iloc[i + 1]['FIRST_SHOT_RESULT']
            )
        else:
            next_result.append(np.nan)

    return pd.Series(
        next_result,
        index=group.index
    )

# Get last shot result from the team's next possession
def next_team_possession_shot_result(group):

    next_result = []

    for i in range(len(group)):

        if i < len(group) - 1:
            next_result.append(
                group.iloc[i + 1]['SHOT_RESULT']
            )
        else:
            next_result.append(np.nan)

    return pd.Series(
        next_result,
        index=group.index
    )

possession_df['SECOND_POSSESSION_SHOT_RESULT'] = (
    possession_df
    .groupby(
        ['GAME_ID', 'PERIOD', 'TEAM'],
        group_keys=False
    )
    .apply(next_team_possession_shot_result)
)

# Only show the second possession for two-for-ones or non-two-for-ones
possession_df['SECOND_POSSESSION_SHOT_RESULT'] = np.where(
    (
        (possession_df['TWO_FOR_ONE_SECOND_POSSESSION?'] == 1)
        |
        (possession_df['NON_TWO_FOR_ONE_SECOND_POSSESSION?'] == 1)
    ),
    possession_df['SECOND_POSSESSION_SHOT_RESULT'],
    np.nan
)

# Get the first shot time from the team's next possession
def next_team_possession_shot_seconds(group):

    next_shot_seconds = []

    for i in range(len(group)):

        if i < len(group) - 1:
            next_shot_seconds.append(
                group.iloc[i + 1]['FIRST_SHOT_SECONDS']
            )
        else:
            next_shot_seconds.append(np.nan)

    return pd.Series(
        next_shot_seconds,
        index=group.index
    )


possession_df['SECOND_POSSESSION_SHOT_SECONDS'] = (
    possession_df
    .groupby(
        ['GAME_ID', 'PERIOD', 'TEAM'],
        group_keys=False
    )
    .apply(next_team_possession_shot_seconds)
)

possession_df['SECOND_POSSESSION_SHOT_SECONDS'] = np.where(
    (
        (possession_df['TWO_FOR_ONE_SECOND_POSSESSION?'] == 1)
        |
        (possession_df['NON_TWO_FOR_ONE_SECOND_POSSESSION?'] == 1)
    ),
    possession_df['SECOND_POSSESSION_SHOT_SECONDS'],
    np.nan
)

# Get points for second possession
possession_df['TWO_FOR_ONE_SECOND_POSSESSION_PTS'] = np.where(
    possession_df['TWO_FOR_ONE_SECOND_POSSESSION?'] == 1,
    possession_df['SECOND_POSSESSION_PTS'],
    np.where(
        possession_df['NON_TWO_FOR_ONE_SECOND_POSSESSION?'] == 1,
        possession_df['SECOND_POSSESSION_PTS'],
        0
    )
)

possession_df['TOTAL_PTS_ON_ALL_2FOR1_POSS'] = possession_df['POSS_PTS'] + possession_df['TWO_FOR_ONE_SECOND_POSSESSION_PTS']

# Filter df for possessions in the final minute where possession length and shot time are not negative
final_minute_df = possession_df[
    (possession_df['START_SECONDS'] <= 60)
    &
    (possession_df['POSS_LENGTH'] > 0)
    &
    (possession_df['SHOT_TIME_FOR_ANALYSIS'] > 0)
]

final_minute_df = final_minute_df[['GAME_ID', 'PERIOD', 'POSSESSION_ID', 'TEAM', 'OPPONENT', 'X_LEGACY', 'Y_LEGACY', 'SHOT_DISTANCE', 'SUBTYPE', 'FIRST_SHOT_PLAYER', 'FIRST_SHOT_RESULT', 
                                   'FIRST_SHOT_VALUE', 'SHOT_TIME_FOR_ANALYSIS', 'CLOCK_SECONDS_LIST', 'TWO_FOR_ONE_ATTEMPT', 'NO_TWO_FOR_ONE_ATTEMPT', 
                                   'POSS_PTS', 'EVENT_LIST', 'NON_TWO_FOR_ONE_SECOND_POSSESSION?', 'TWO_FOR_ONE_SECOND_POSSESSION?', 'TWO_FOR_ONE_SECOND_POSSESSION_PTS', 'TOTAL_PTS_ON_ALL_2FOR1_POSS']]

In [ ]:
import re
import unicodedata

# Get player and team logo images

team_logos = pd.read_csv(f'{file_path}/team_logos.csv', index_col=0)
player_images = pd.read_csv(f'{file_path}/player_images.csv', index_col=0)

def normalize_player_name_for_matching(name):

    if pd.isna(name):
        return name

    # Remove accents
    name = ''.join(
        c for c in unicodedata.normalize('NFD', str(name))
        if unicodedata.category(c) != 'Mn'
    )

    # Remove suffixes
    name = re.sub(
        r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$',
        '',
        name,
        flags=re.IGNORECASE
    )

    # Remove extra whitespace
    name = re.sub(r'\s+', ' ', name).strip()

    # Split name
    parts = name.split()

    if len(parts) < 2:
        return name.lower()

    # First initial + last name
    return f'{parts[0][0]}. {parts[-1]}'.lower()


team_abbrev_map = {
    'Atlanta Hawks': 'ATL',
    'Boston Celtics': 'BOS',
    'Brooklyn Nets': 'BKN',
    'Charlotte Hornets': 'CHA',
    'Chicago Bulls': 'CHI',
    'Cleveland Cavaliers': 'CLE',
    'Dallas Mavericks': 'DAL',
    'Denver Nuggets': 'DEN',
    'Detroit Pistons': 'DET',
    'Golden State Warriors': 'GSW',
    'Houston Rockets': 'HOU',
    'Indiana Pacers': 'IND',
    'LA Clippers': 'LAC',
    'Los Angeles Lakers': 'LAL',
    'Memphis Grizzlies': 'MEM',
    'Miami Heat': 'MIA',
    'Milwaukee Bucks': 'MIL',
    'Minnesota Timberwolves': 'MIN',
    'New Orleans Pelicans': 'NOP',
    'New York Knicks': 'NYK',
    'Oklahoma City Thunder': 'OKC',
    'Orlando Magic': 'ORL',
    'Philadelphia 76ers': 'PHI',
    'Phoenix Suns': 'PHX',
    'Portland Trail Blazers': 'POR',
    'Sacramento Kings': 'SAC',
    'San Antonio Spurs': 'SAS',
    'Toronto Raptors': 'TOR',
    'Utah Jazz': 'UTA',
    'Washington Wizards': 'WAS'
}

team_logos['TEAM_ABBREV'] = (
    team_logos['team']
    .map(team_abbrev_map)
)

player_images['Player_Normalized'] = (
    player_images['Player']
    .apply(normalize_player_name_for_matching)
)

team_logos = team_logos[['team', 'TEAM_ABBREV', 'logo']]
player_images = player_images[player_images['Team'] != '2TM']
player_images["Team"] = player_images["Team"].replace({
    'PHO': 'PHX',
    'CHO': 'CHA',
    'BRK': 'BKN'
})
player_images = player_images[['Player','Player_Normalized', 'Team', 'Images']]

In [166]:
# Create final dataframe with player and team images

filtered_df = possession_df[
    (possession_df['TWO_FOR_ONE_ATTEMPT'] == 1)
    |
    (possession_df['NO_TWO_FOR_ONE_ATTEMPT'] == 1)
].copy()

filtered_df = filtered_df[filtered_df['TIME_UNTIL_FIRST_SHOT'] >= 0]

filtered_df['PLAYER_NAME_NORMALIZED'] = (
    filtered_df['FIRST_SHOT_PLAYER']
    .apply(normalize_player_name_for_matching)
)

pbp_logos_df = filtered_df.merge(team_logos, how='left', left_on='TEAM', right_on='TEAM_ABBREV')
final_df = pbp_logos_df.merge(player_images, how='left', left_on=['PLAYER_NAME_NORMALIZED', 'TEAM'], right_on=['Player_Normalized', 'Team'])
final_df = final_df.drop_duplicates(subset=['GAME_ID', 'PERIOD', 'POSSESSION_ID', 'PLAYER_NAME'])
keep_columns = ['GAME_ID','POSSESSION_ID','PERIOD','START_CLOCK','END_CLOCK','EVENTS','ACTION_TYPES','EVENT_LIST','TEAM','team','TEAM_ID','PLAYER_ID','PLAYER_NAME',
                'HOME_SCORE','AWAY_SCORE','FIRST_SHOT_RESULT','FIRST_SHOT_VALUE','FIRST_SHOT_SUBTYPE','FIRST_SHOT_PLAYER','FIRST_SHOT_X_LEGACY','FIRST_SHOT_Y_LEGACY',
                'FIRST_SHOT_DISTANCE','FIRST_SHOT_SECONDS','POSS_LENGTH','TIME_UNTIL_FIRST_SHOT','SHOT_TIME_FOR_ANALYSIS','TWO_FOR_ONE_ATTEMPT',
                'NO_TWO_FOR_ONE_ATTEMPT','POSS_PTS','FREE_THROW_PTS','TWO_FOR_ONE_SECOND_POSSESSION?','NON_TWO_FOR_ONE_SECOND_POSSESSION?','SECOND_POSSESSION_PTS',
                'SECOND_POSSESSION_SHOT_RESULT','SECOND_POSSESSION_SHOT_SECONDS','TWO_FOR_ONE_SECOND_POSSESSION_PTS','TOTAL_PTS_ON_ALL_2FOR1_POSS','TEAM_ABBREV',
                'logo','Player','Images']

final_df = final_df[keep_columns]

final_df = final_df[
    ~(
        (final_df["EVENTS"] == 1) &
        ((final_df["FIRST_SHOT_SECONDS"] + final_df["POSS_LENGTH"]) > 40)
    )
]

final_df.to_csv(
    f'{file_path}/final_2for1_stats.csv',
    index=False
)

In [168]:
two_for_one_shots = (final_df['TWO_FOR_ONE_ATTEMPT'] == 1).sum()
non_two_for_one_shots = (final_df['NO_TWO_FOR_ONE_ATTEMPT'] == 1).sum()

print(f'Two for One Shot Attempts: {two_for_one_shots}')
print(f'Non Two for One Shot Attempts: {non_two_for_one_shots}')

Two for One Shot Attempts: 582
Non Two for One Shot Attempts: 196

In [169]:
import pandas as pd
import numpy as np

# Keep only rows with a valid first-shot distance
shot_df = final_df[
    final_df["FIRST_SHOT_DISTANCE"].notna()
].copy()

# Create distance buckets
bins = [0, 5, 10, 15, 20, 25, np.inf]
labels = [
    "0-5 feet",
    "5-10 feet",
    "10-15 feet",
    "15-20 feet",
    "20-25 feet",
    "25+ feet"
]

shot_df["DISTANCE_BUCKET"] = pd.cut(
    shot_df["FIRST_SHOT_DISTANCE"],
    bins=bins,
    labels=labels,
    right=False  # 0-5 includes 0 through <5
)

# 2-for-1 distribution
two_dist = (
    shot_df[shot_df["TWO_FOR_ONE_ATTEMPT"] == 1]
    .groupby("DISTANCE_BUCKET", observed=False)
    .size()
    .pipe(lambda x: x / x.sum() * 100)
    .round(1)
)

# Non-2-for-1 distribution
non_dist = (
    shot_df[shot_df["NO_TWO_FOR_ONE_ATTEMPT"] == 1]
    .groupby("DISTANCE_BUCKET", observed=False)
    .size()
    .pipe(lambda x: x / x.sum() * 100)
    .round(1)
)

# Combine into one table
distance_table = pd.DataFrame({
    "2-for-1 %": two_dist,
    "Non-2-for-1 %": non_dist
}).fillna(0)

print(distance_table)

                 2-for-1 %  Non-2-for-1 %
DISTANCE_BUCKET
0-5 feet              39.9           29.1
5-10 feet             11.0           14.3
10-15 feet             4.0            6.1
15-20 feet             2.9            7.7
20-25 feet             5.3            6.6
25+ feet              36.9           36.2